version: "3.8"
services:
  quicksign:
    build:
      context: .
      dockerfile: Dockerfile
    image: quicksign
    container_name: quicksign-server
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: mongodb://mongodb:27017/quicksign
      NODE_ENV: development
      JWT_SECRET: something
      COOKIE_SECRET: something
      PORT: 1344
      MONGO_USER: ""
      MONGO_PASSWORD: ""
      MONGO_DB_NAME: quicksign
      MONGO_PORT: 27017
      MONGO_HOST: mongodb
    ports:
      - 1344:1344
    volumes:
      - .:/app/quicksign
      - node_modules:/app/quicksign/node_modules
    networks:
      - iddrink_network
  mongodb:
    image: mongo:5.0
    ports:
      - 27018:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_USER=
      - MONGO_PASSWORD=
      - MONGO_DB_NAME=quicksign
      - MONGO_PORT=27017
      - MONGO_HOST=127.0.0.1
    networks:
      - iddrink_network
  redis:
    image: redis
    ports:
      - 6380:6380
    networks:
      - iddrink_network
volumes:
  node_modules:

networks:
  iddrink_network:
    driver: bridge
